
import { Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'zh', name: 'Mandarin Chinese', native: '中文' },
  { code: 'yue', name: 'Canton Chinese', native: '廣東話' },
  { code: 'zh-TW', name: 'Taiwanese Mandarin', native: '繁體中文' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'jv', name: 'Javanese', native: 'Basa Jawa' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'ਮਰਾठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'my', name: 'Burmese', native: 'မြန်မာစာ' },
  { code: 'ha', name: 'Hausa', native: 'Hausa' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'cs', name: 'Czech', native: 'Čeština' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'az', name: 'Azerbaijani', native: 'Azərbaycanca' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbekcha' },
  { code: 'kk', name: 'Kazakh', native: 'Қазақ тілі' },
  { code: 'si', name: 'Sinhala', native: 'සිංහල' },
  { code: 'km', name: 'Khmer', native: 'ខ្មែរ' },
  { code: 'lo', name: 'Lao', native: 'ລາວ' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'ps', name: 'Pashto', native: 'ਪښتو' },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
  { code: 'tl', name: 'Tagalog', native: 'Tagalog' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina' },
  { code: 'bg', name: 'Bulgarian', native: 'Български' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'sr', name: 'Serbian', native: 'Српски' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
  { code: 'sq', name: 'Albanian', native: 'Shqip' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
  { code: 'ka', name: 'Georgian', native: 'ქართული' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'mt', name: 'Maltese', native: 'Malti' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge' },
  { code: 'gd', name: 'Scottish Gaelic', native: 'Gàidhlig' },
  { code: 'eu', name: 'Basque', native: 'Euskara' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'ca', name: 'Catalan', native: 'Català' },
  { code: 'be', name: 'Belarusian', native: 'Беларуская' },
  { code: 'mk', name: 'Macedonian', native: 'Македонски' },
  { code: 'ky', name: 'Kyrgyz', native: 'Кыргызча' },
  { code: 'tg', name: 'Tajik', native: 'Тоҷикӣ' },
  { code: 'tk', name: 'Turkmen', native: 'Türkmençe' },
  { code: 'mn', name: 'Mongolian', native: 'Монгол' },
  { code: 'ti', name: 'Tigrinya', native: 'ትግርኛ' },
  { code: 'om', name: 'Oromo', native: 'Oromoo' },
  { code: 'so', name: 'Somali', native: 'Soomaali' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo' },
  { code: 'ny', name: 'Chichewa', native: 'Chichewa' },
  { code: 'sn', name: 'Shona', native: 'chiShona' },
  { code: 'rw', name: 'Kinyarwanda', native: 'Ikinyarwanda' },
  { code: 'mg', name: 'Malagasy', native: 'Malagasy' },
  { code: 'ln', name: 'Lingala', native: 'Lingála' },
  { code: 'st', name: 'Sesotho', native: 'Sesotho' },
  { code: 'tn', name: 'Tswana', native: 'Setswana' },
  { code: 'ts', name: 'Tsonga', native: 'Xitsonga' },
  { code: 've', name: 'Venda', native: 'Tshivenda' },
  { code: 'ss', name: 'Swati', native: 'SiSwati' },
  { code: 'nr', name: 'Southern Ndebele', native: 'isiNdebele' },
];
